### ISSUE TITLE
Почему-то нельзя включить переносы в тексте.

### ISSUE THREAD

**Issue by otec666** [YarGU-Demidov/MathSiteLayout#16]
Без переносов, если выравнивать текст, то получаются неприятные промежутки.

**Comment by mokeev1995** [comment]
@otec666 хмм, а пример заскринь и кинь сюда

**Comment by otec666** [comment]
![2016-04-21 23 31 30](https://cloud.githubusercontent.com/assets/18498716/14723359/4c1577dc-0819-11e6-91d7-cb2711d94635.png)

**Comment by mokeev1995** [comment]
@otec666 стоп, а чем не нравятся родные переносы?

**Comment by otec666** [comment]
Какие родные?

**Comment by mokeev1995** [comment]
@otec666 ну, которые делаются автоматически. 1 enter == 1 новый абзац. если он пустой, то это не отменяет присутствия отступов, которые делаются для него автоматически.

**Comment by otec666** [comment]
Я имею ввиду перенос слов. Т.е. У меня не влезает слово "карнавал" в строчку и его хотелось бы разделить. Написать часть на одной строчке, а часть на другой

**Comment by mokeev1995** [comment]
@otec666 чем не устраивает перенос всего слова сразу и чтоб об этом не задумываться? браузер умный, он сумеет перенести слово.

**Comment by otec666** [comment]
ужасно выглядит

**Comment by mokeev1995** [comment]
@otec666 на самом деле я вообще не вижу, где там переносы были сделаны.

**Comment by mokeev1995** [comment]
@otec666 можешь выделить именно те места, где делались переносы?

**Comment by otec666** [comment]
Они никогда не делались

**Comment by mokeev1995** [comment]
@otec666 а где должны были?

**Comment by otec666** [comment]
в конце строк в которые слова не влезают. Ты чего вордовские документы никогда не видел?

**Comment by mokeev1995** [comment]
Всё работает.
