### ISSUE TITLE
СРОЧНОООО!!! Шаблон страницы контактов!

### ISSUE THREAD

**Issue by mokeev1995** [YarGU-Demidov/MathSiteLayout#25]
Его просто нет, хотя должон быть, он особняком стоит!

**Comment by otec666** [comment]
Можно просто текстовую страницу сделать.

**Comment by mokeev1995** [comment]
нельзя

**Comment by mokeev1995** [comment]
вот это надо добавить!

![2016-05-08_19-00-11](https://cloud.githubusercontent.com/assets/8450876/15098836/20da28ea-154f-11e6-986a-1fe5f38d9f6f.png)

**Comment by mokeev1995** [comment]
@alinastart поправь шаблон так, чтоб оно максимально похоже было на это (я про иконки соц.сетей, адрес, телефон)

**Comment by mokeev1995** [comment]
done

**Comment by mokeev1995** [comment]
#36
