### ISSUE TITLE
Страница новостей.

### ISSUE THREAD

**Issue by otec666** [YarGU-Demidov/MathSiteLayout#6]
1. Указаны контактные данные биологического факультета вместо математического(в голубом прямоугольнике).

2. При попытке загрузить фото к новости, он размазывается на весь экран, выезажая за все границы. 

3. Под надписями "Новости, события, фотогалерея" Какое-то место под картинку, что там должно быть? Почему ничего не отображается.

![default](https://cloud.githubusercontent.com/assets/18498716/14580653/4421e9e2-03dd-11e6-95fe-e98aa71cb31d.png)

**Comment by alinastart** [comment]
исправлено
