### ISSUE TITLE
Испорчены расстояния между абзацами

### ISSUE THREAD

**Issue by mokeev1995** [YarGU-Demidov/MathSiteLayout#7]
Стало:
![1](https://cloud.githubusercontent.com/assets/8450876/14581306/2d5f5b9e-03f2-11e6-8a2d-3a0aa29ccd7d.png)

Было:
![2](https://cloud.githubusercontent.com/assets/8450876/14581307/2f77696c-03f2-11e6-9b56-6c31f4d76a5c.png)

**Comment by alinastart** [comment]
исправлено
