### ISSUE TITLE
в HTML тегах встречаются style свойства

### ISSUE THREAD

**Issue by mokeev1995** [YarGU-Demidov/MathSiteLayout#8]
на странице entrant в тексте куууча просто таким образом стилизованых эл-тов. это крайне неверный подход для выделения особенного текста(ну, так можно делать только для тега span, и то, специально, зная, что так сможет сделать редактор в CMS). всякие ссылки требуется выделять в CSS!

**Comment by alinastart** [comment]
исправлено
